name: hls_network
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.2.19
  flutter_launcher_icons: ^0.12.0
  shared_preferences: ^2.0.20
  provider: ^6.0.5
  curved_navigation_bar: ^1.0.3
  google_fonts: ^4.0.4
  http: ^0.13.6
  cloud_firestore: ^4.7.1
  firebase_storage: ^11.2.1
  flutter_riverpod: ^2.3.6
  image_picker: ^0.8.7+5
  cached_network_image: ^3.2.3
  random_string: ^2.3.1
  multiple_images_picker: ^1.0.1
  carousel_slider: ^4.2.1
  flutter_svg: ^2.0.5
  uuid: ^3.0.7
  fpdart: ^0.6.0
  any_link_preview: ^3.0.0
  timeago: ^3.4.0
  like_button: ^2.0.5
  sliding_up_panel: ^2.0.0+1
  photo_view: ^0.14.0
  share_plus: ^7.0.2
  path_provider: ^2.0.15
  url_launcher: ^6.1.11
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  intl: ^0.18.1


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher.png"
  web:
  generate: true
  background_color: "#37678a"
  theme_color: "#ffffff"
  
flutter_native_splash:
  image: assets/appicon.png
  color: "#37678a"
  android_gravity: center
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

