// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdUJCQkZu0oiUFp2HtsRppq8TBmEgMr4c',
    appId: '1:912898352075:web:91ece16a2141177ab44c4e',
    messagingSenderId: '912898352075',
    projectId: 'hlsnetworkbackend',
    authDomain: 'hlsnetworkbackend.firebaseapp.com',
    storageBucket: 'hlsnetworkbackend.appspot.com',
    measurementId: 'G-8BP6MF0BVF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-jny5U0bD3-TvcK4DVHyY8RArhfAlM_k',
    appId: '1:912898352075:android:e1064583ac3e8960b44c4e',
    messagingSenderId: '912898352075',
    projectId: 'hlsnetworkbackend',
    storageBucket: 'hlsnetworkbackend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ7SUK6dC5MCebRw2qbT08npmX-5BQD3M',
    appId: '1:912898352075:ios:5f60f91036b36d81b44c4e',
    messagingSenderId: '912898352075',
    projectId: 'hlsnetworkbackend',
    storageBucket: 'hlsnetworkbackend.appspot.com',
    iosClientId: '912898352075-bdmc5d8993s9svfv3t95fibobhgbegt8.apps.googleusercontent.com',
    iosBundleId: 'com.example.hlsNetwork',
  );
}
